# Generated by Django 4.2.5 on 2023-09-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work_samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=10, verbose_name='نام پروژه')),
                ('avatar_project', models.FileField(blank=True, null=True, upload_to='images/image_project', verbose_name='تصویر پروژه')),
                ('link_field', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر آواتار')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(max_length=30, verbose_name='جنسیت')),
                ('marital_status', models.CharField(max_length=30, verbose_name='مجرد / متاهل')),
                ('date_of_birth', models.DateField(auto_now_add=True, verbose_name='تاریخ تولد')),
                ('phone', models.IntegerField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل ')),
                ('samples_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subapp.work_samples')),
            ],
            options={
                'verbose_name': 'نکات مهم رزومه شما',
                'verbose_name_plural': 'نکته های مهم رزومه شما',
            },
        ),
    ]
