# Generated by Django 4.2.5 on 2023-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_samples',
            options={'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها '},
        ),
        migrations.AlterField(
            model_name='work_samples',
            name='name_project',
            field=models.CharField(max_length=200, verbose_name='نام پروژه'),
        ),
    ]
