# Generated by Django 4.2.5 on 2023-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_alter_work_samples_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='phone',
            field=models.IntegerField(verbose_name='شماره تماس'),
        ),
    ]
