# Generated by Django 4.2.5 on 2023-10-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_alter_me_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], max_length=30, verbose_name='جنسیت'),
        ),
    ]
