# Generated by Django 4.2.5 on 2023-10-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_alter_me_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن '), ('unknown', 'ترجیح می دهم نگویم ')], max_length=30, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='me',
            name='marital_status',
            field=models.CharField(choices=[('single', 'مجرد'), ('marrid', 'متاهل ')], max_length=30, verbose_name='وضعیت تاهل '),
        ),
        migrations.AlterField(
            model_name='me',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='me',
            name='samples_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subapp.work_samples', verbose_name='نمونه کار '),
        ),
    ]
