# Generated by Django 4.2.5 on 2023-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0005_alter_me_gender_alter_me_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر آواتار'),
        ),
    ]
