# Generated by Django 4.2.5 on 2023-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0006_alter_me_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='Scientific_position',
            field=models.CharField(default=1, max_length=30, verbose_name='جایگاه علمی شما'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='me',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/profile', verbose_name='تصویر آواتار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='me',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
    ]
