# Generated by Django 4.2.5 on 2023-10-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0009_alter_me_options_me_military_service_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='Requested_stipend',
            field=models.IntegerField(default=15000000, max_length=30, verbose_name='حقوق درخواستی شما'),
            preserve_default=False,
        ),
    ]
