# Generated by Django 4.2.5 on 2023-10-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0011_work_experience_me_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='work_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subapp.work_experience', verbose_name='عناوین شغلی'),
            preserve_default=False,
        ),
    ]
