# Generated by Django 4.2.5 on 2023-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0012_me_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='biography',
            field=models.TextField(max_length=600, verbose_name='بیوگرافی'),
        ),
    ]
