# Generated by Django 4.2.5 on 2023-10-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0014_educational_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='Educational_records',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subapp.educational_records', verbose_name='سابقه تحصیلی'),
            preserve_default=False,
        ),
    ]
