# Generated by Django 4.2.5 on 2023-10-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0016_interests_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='mastery_level',
            field=models.CharField(choices=[('مبتدی', 'مبتدی'), ('متوسط', 'متوسط '), ('حرفه ای ', 'حرفه ای  '), ('تسلط کامل', 'تسلط کامل')], default=1, max_length=10, verbose_name='سطح تسلط'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languages',
            name='mastery_level',
            field=models.CharField(choices=[('مبتدی', 'مبتدی'), ('متوسط', 'متوسط '), ('حرفه ای ', 'حرفه ای  '), ('تسلط کامل', 'تسلط کامل')], default=1, max_length=10, verbose_name='سطح تسلط'),
            preserve_default=False,
        ),
    ]
