# Generated by Django 4.2.5 on 2023-10-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0017_interests_mastery_level_languages_mastery_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='mastery_level',
        ),
    ]
