# Generated by Django 4.2.5 on 2023-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0018_remove_interests_mastery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_samples',
            name='description',
            field=models.TextField(default=1, max_length=600, verbose_name='توضیحات راجب نمونه کار'),
            preserve_default=False,
        ),
    ]
