# Generated by Django 4.2.5 on 2023-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0019_work_samples_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان مهارت')),
                ('Percent', models.CharField(choices=[('10', '10'), ('20', '20 '), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=30, verbose_name='درصد مهارت شما ')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
    ]
